language: node_js
node_js:
- stable
services:
  - mysql
cache:
  directories:
  - node_modules
before_install:
  - mysql -e "CREATE USER 'turing'@'localhost' IDENTIFIED BY 'test';"
  - mysql -e 'CREATE DATABASE test;'
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'turing'@'localhost';"
  - npm install -g sequelize-cli
before_script:
  - npm install codeclimate-test-reporter -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - npm test
after_script:
  - npm run coverage
